#include "include.h"

class $modify(DeltaruneAlertLayer, FLAlertLayer) {
	struct Fields {
		bool hasChoice = false;
		bool reverseAnim = false;
		bool showing = false;
		bool incompatible = false;
		bool dialog = false;
		bool noShadow = false;
		CCSpriteGrayscale* characterSprite;
		bool doneRolling = false;
		bool rolledPage = false;
		int waitQueue = 0;
		int frame = 0;
		int rollingLine = 0;
		int linesProgressed = 0;
		bool playedSound = false;
		int characterCount = 0;
		bool done = false;
		std::string text = "";
		std::string textSound = Mod::get()->getSettingValue<std::string>("textSound");
		float screenSize = CCDirector::sharedDirector()->getWinSize().width;
		int textSize = 36;
		int btnSelected = 0;
		bool dontRestrictWidth = Mod::get()->getSettingValue<bool>("dontRestrictWidth");
		bool disableClickToProgress = Mod::get()->getSettingValue<bool>("disableClickToProgress");
		CCNode* btn1;
		CCNode* btn2;
		CCNode* textAreaClippingNode;
		CCNode* textArea;
		CCNode* gradientOverlay;
		CCNode* shadow;
		CCNode* bg;
		CCSprite* heart;
		CCLabelBMFont* title;
		FMOD::System* system = FMODAudioEngine::sharedEngine()->m_system;
		FMOD::Channel* channel;
		FMOD::Sound* sound;
	};
	void animateBG(float);
	void changeBG();
	void changeButtons();
	void changeTitle();
	void changeText();
	void changeLook();
	void decideToBlockKeys();
	void show() override;
	bool init(FLAlertLayerProtocol*, char const*, gd::string, char const*, char const*, float, bool, float, float);
	void rollText(float);
	void showButtons();
	void setHeartPosition(CCNode*);
	int getLinesLeft();
	void skipText();
	void progressText();
	// I can't check for enter key so I guess I have to hook the buttons
	void onBtn2(CCObject*);
	void onBtn1(CCObject*);
	bool ccTouchBegan(CCTouch*, CCEvent*) override;
	void keyDown(enumKeyCodes) override;
};